title: Rayzer0 
author: GitHub User
email: rayferrufino@gmail.com
description:



  Hi folks! Welcome to my personal blog where I write about pentesting
  and cybersecurity :) 
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 6
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://linkedin.com/in/ray-ferrufino/
      icon: linkedin
      color: blue
    - url: https://www.hackthebox.eu/profile/169983
      icon: redhat
      color: red
    - url: https://github.com/Rayferrufino
      icon: github-square
      color: teal
       

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
