title: Rayzer0 
author: GitHub User
email: rayferrufino@gmail.com
description: 
  <img src="https://lh3.googleusercontent.com/46mIeATwjKgNUC6Kiz6K_uGM_g4lcum0nD-DTFnT86Xic_gCWyIVkolb3l2v8dYuTsX0ipflDHrz_JGwZxWJ0e5vfWLqwFhAZ_7fED9oCBGLALE2Uy-ZnQmZ3EZIxpNakf7xhhEQRy5xj603Zp6yejRiAP77knw1M4Gvb0rzBVTf1mO4SqwV3-vgOKaxzNC5kcaa0tizAJgg9xBuZjHfmSK3ZC0RVr5TYJ45VNLM923m5KBWlochR1zPjIYRwNc3Uig2w0Owrgwi1j8k4KMRk8DilMo6PoO-0yWiUknTelBaHAWxGqfmKtFPveS0pD9rHedmFitsMtQWZvSPagMNJ25WrE7eJ1mKfkSrP91RCCTfzXnc9QuQOxlriLFojbNF2tbTPOZnfYyNmwRW6m_UlL4AR1bQIJqYWZkkcCOtUjGYoxU-tghlqEeD5QIMNtGNZk9jsqSY3HH01eyxVhvi5Bvd67EJgOAGKT5dWnU4tdu2gF9fP5vkB-lqqmknFfWW9rM_UcipSm6pK5V-QISKzc4-CgMMgC9qKzkJQsE0BymXVxk0SlaiBMgpGFjjMFErzkZn3fN3If3Q-PBXUen1a3olfR3i2XRrw69guWQCuQPe31OnLQs7sEvzBC8QLH9bgG2XWd9gJlxJmhOQQjZbn3rVurk2LJVFXfMKnz1aEtY89ErYl4gYAhI=w492-h376-no" alt="Smiley face" height="200" width="350">
  ....RmVlbCBmcmVlIHRvIHJlYWNoIGF0IHJheWZlcnJ1Zmlub0BnbWFpbC5jb20=  Hi Folks! Welcome to my blog where I write about pentesting, cybersecurity and occasionally about videogames :)
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 6
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://linkedin.com/in/ray-ferrufino/
      icon: linkedin
      color: blue
    - url: https://www.hackthebox.eu/profile/169983
      icon: redhat
      color: red
    - url: https://github.com/Rayferrufino
      icon: github-square
      color: teal
       

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
